// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed_follows.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
with inserted_feed_follow as (
  insert into feed_follows (user_id, feed_id)
  values ($1, $2)
  returning id, created_at, updated_at, user_id, feed_id
) 
select inserted_feed_follow.id, inserted_feed_follow.created_at, inserted_feed_follow.updated_at, inserted_feed_follow.user_id, inserted_feed_follow.feed_id, users.name as user_name, feeds.name as feed_name
from inserted_feed_follow
inner join users on inserted_feed_follow.user_id = users.id
inner join feeds on inserted_feed_follow.feed_id = feeds.id
`

type CreateFeedFollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

type CreateFeedFollowRow struct {
	ID        int32
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	UserName  string
	FeedName  string
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow, arg.UserID, arg.FeedID)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.UserName,
		&i.FeedName,
	)
	return i, err
}

const getFollowing = `-- name: GetFollowing :many
select feed_follows.user_id as user_id, feeds.id, feeds.created_at, feeds.updated_at, feeds.name, feeds.url, feeds.user_id from feed_follows
inner join feeds on feed_follows.feed_id = feeds.id
where feed_follows.user_id = $1
`

type GetFollowingRow struct {
	UserID    uuid.UUID
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	UserID_2  uuid.UUID
}

func (q *Queries) GetFollowing(ctx context.Context, userID uuid.UUID) ([]GetFollowingRow, error) {
	rows, err := q.db.QueryContext(ctx, getFollowing, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFollowingRow
	for rows.Next() {
		var i GetFollowingRow
		if err := rows.Scan(
			&i.UserID,
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.UserID_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfollowFeedUrl = `-- name: UnfollowFeedUrl :exec
delete from feed_follows
where feed_follows.user_id = $1 and feed_follows.feed_id =  (
  select id from feeds
  where feeds.url = $2
)
`

type UnfollowFeedUrlParams struct {
	UserID uuid.UUID
	Url    string
}

func (q *Queries) UnfollowFeedUrl(ctx context.Context, arg UnfollowFeedUrlParams) error {
	_, err := q.db.ExecContext(ctx, unfollowFeedUrl, arg.UserID, arg.Url)
	return err
}
