-- +goose Up
create table posts (
  id int generated by default as identity primary key,
  created_at timestamp not null default now (),
  updated_at timestamp not null default now (),
  title text not null,
  url text not null unique,
  description text not null,
  published_at timestamp not null,
  feed_id uuid not null references feeds (id) on delete cascade
);

-- +goose Down
drop table posts;
